version: "3"
services:
  server:
    image: brymonsoft-messenger-rest-api
    build: ./
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
